wandb_version: 1

K:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.25.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1671759116.661128
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.5
      5: 0.13.7
      6: 4.25.1
      8:
      - 5
activation_function:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: medium
device:
  desc: null
  value: cuda
dropout:
  desc: null
  value: 0.1
embed_dim:
  desc: null
  value: 128
env:
  desc: null
  value: hopper
learning_rate:
  desc: null
  value: 0.0001
load_model:
  desc: null
  value: 'NO'
log_to_wandb:
  desc: null
  value: true
max_iters:
  desc: null
  value: 2000
mode:
  desc: null
  value: normal
model_type:
  desc: null
  value: dt
n_head:
  desc: null
  value: 1
n_layer:
  desc: null
  value: 4
n_layer_critics:
  desc: null
  value: 3
num_eval_episodes:
  desc: null
  value: 3
num_steps_per_iter:
  desc: null
  value: 50
pct_traj:
  desc: null
  value: 1.0
save_model:
  desc: null
  value: 'NO'
seeds:
  desc: null
  value: 0 1 2
warmup_steps:
  desc: null
  value: 10000
weight_decay:
  desc: null
  value: 0.0001
